# Generated by Django 6.0 on 2026-01-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_hash', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Hash ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('time_entry', models.BigIntegerField(default=0, verbose_name='Hora de Entrada (Unix)')),
                ('time_exit', models.BigIntegerField(default=0, verbose_name='Hora de Salida (Unix)')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'data',
            },
        ),
    ]
