# Generated by Django 6.0.7 on 2026-07-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono Celular"
            ),
        ),
    ]
